name: "Daily activity digests"
on:
  push:
  schedule:
    # 1pm UTC, so 8/9am Eastern.
    # https://crontab.guru/#02_13_*_*_*
    - cron: "02 13 * * *"
  workflow_dispatch:
jobs:
  digest:
    name: "Daily digest"
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: "Install dinghy"
        run: |
          python -m pip install dinghy
      - name: "Run dinghy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m dinghy
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: prod
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
